Add feature to keep suggestions after approving/rejecting
suggestionsbot/suggestions-docs pull request #4
Opened 2022-02-14 01:00 UTC by acollierr17

This is in sync with the new `keepLogs` configuration that's been introduced over at Add feature to keep suggestions after approving/rejecting

2022-02-14 02:33 UTC, acollierr17 commented
@Davi-the-Mudkip You have any grammar things you like me to add on/consider here?

2022-02-16 00:39 UTC, Davi-the-Mudkip commented
6

2022-02-16 00:40 UTC, Davi-the-Mudkip requested changes
Here are my comments:

2022-02-16 00:40 UTC, Davi-the-Mudkip commented on docs/docs/managing-suggestions.md
> +* The results of that suggestion will either be posted to the suggestion logs channel or the suggestion message will be kept with its results displayed. (dependent on [`config keepLogs`](configuratio
For the sake of parallel structure:

```suggestion
* The results of that suggestion will either be posted to the suggestion logs channel or be kept in the suggestion message. (dependent on [`config keepLogs`](configuration.md#keep-logs))
```

2022-02-16 00:40 UTC, Davi-the-Mudkip commented on docs/docs/managing-suggestions.md
> +- If you have a suggestion logs channel set and `config keepLogs` is false, The bot will delete the original suggestion message and its results posted to the set logs channel. You'll find the followi
A small typo:
```suggestion
- If you have a suggestion logs channel set and `config keepLogs` is false, the bot will delete the original suggestion message and its results will be posted to the set logs channel. You'll find the following information in the log message either way:
```

2022-02-16 00:40 UTC, Davi-the-Mudkip commented on docs/docs/managing-suggestions.md
> +If you wish to set up a suggestion logs channel, you may refer to the [Getting Started](README.md#setting-up-the-bot) section of the documentation.
This line should appear after the information list.

2022-02-16 00:40 UTC, Davi-the-Mudkip commented on docs/docs/configuration.md
> +3) The submitter (if DM responses are enabled) will be DMed that their suggestion has been processed
These list items should end with a period as they're complete sentences:
```suggestion
1) The suggestion message will be updated with its status and result.
2) The reactions will be removed from the message.
3) The submitter (if DM responses are enabled) will be DMed that their suggestion has been processed.
```

2022-02-16 01:44 UTC, acollierr17 commented on docs/docs/managing-suggestions.md
> +If you wish to set up a suggestion logs channel, you may refer to the [Getting Started](README.md#setting-up-the-bot) section of the documentation.
Should I put it after line 49?

2022-02-16 16:47 UTC, Davi-the-Mudkip commented on docs/docs/managing-suggestions.md
> +If you wish to set up a suggestion logs channel, you may refer to the [Getting Started](README.md#setting-up-the-bot) section of the documentation.
No, you should put it after line 83.

2022-02-16 16:53 UTC, acollierr17 commented on docs/docs/managing-suggestions.md
> +If you wish to set up a suggestion logs channel, you may refer to the [Getting Started](README.md#setting-up-the-bot) section of the documentation.
Got it,

2022-02-16 16:56 UTC, acollierr17 reviewed
All changes from the code review have been resolved. Should be good to go.

2022-02-20 00:33 UTC, merged